### ISSUE TITLE
Add candidate network edge documentation

### ISSUE THREAD

**Issue by Boarders** [amnh/PCG#128]
The tests in https://github.com/amnh/PCG/issues/105 revealed several things that we had not considered as far as testing compatibility when adding network edges. 

In total if edge1 = (src1, tgt1) and edge2 = (src2, tgt2) we currently test:
 - if either edge1 or edge 2 is ancestral to one another.
 - If edge1 or edge2 is implied to be ancestral to one another by a ancestral network event.
 - If edge2 is a network edge.
 - If we have a network event:
```
p1     p2
 \     /
    n
```
we say p2 is the network pair of p1. If e1 is a network edge i.e. an edge of the form (p1, n) in the above diagram then we have to check that p2 is not ancestral to e2. Similarly if the source of e2 is a parent of a network node then we must check that the network pair of src2 is not ancestral to e1.
- Currently we also optionally check if either e1 or e2 is adjacent to the root and if so we exclude it.

We should add documentation for these different cases including diagrams explaining why they are disallowed.

**Comment by wardwheeler** [comment]
So late….

On Mar 13, 2019, at 9:00 PM, Boarders <notifications@github.com<mailto:notifications@github.com>> wrote:


The tests in #105<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Famnh%2FPCG%2Fissues%2F105&data=01%7C01%7Cwheeler%40amnh.org%7Ca5c53fdfff6b4682985a08d6a8186932%7Cbe0003e8c6b9496883aeb34586974b76%7C0&sdata=wSj832KmPEXiYEPQ%2FaJWNVCQqstwaykH7av%2BRbkT6UU%3D&reserved=0> revealed several things that we had not considered as far as testing compatibility of edges when adding network edges.
In total if edge1 = (src1, tgt1) and edge2 = (src2, tgt2) we test:

  *   if edge1 or edge 2 is ancestral to one another.
  *   If edge1 or edge2 is implied to be ancestral to one another by a ancestral network event.
  *   If edge2 is a network edge
  *   If we have a network event:

p1     p2
 \       /
    n


we say p2 is the network pair of p1. If e1 is a network edge i.e. an edge of the form (p1, n) in the above diagram then we have to check that p2 is not ancestral to e2. Similarly if the source of e2 is a parent of a network node then we must check that the network pair of src2 is not ancestral to e1.

  *   Currently we also optionally check if either e1 or e2 is adjacent to the root and if so we exclude it.

We should add documentation for these different cases including diagrams explaining why they are disallowed.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Famnh%2FPCG%2Fissues%2F128&data=01%7C01%7Cwheeler%40amnh.org%7Ca5c53fdfff6b4682985a08d6a8186932%7Cbe0003e8c6b9496883aeb34586974b76%7C0&sdata=EIGBNflApyhCXkekAuK1soVGoUMZU9dOJ%2FroRZ8czj0%3D&reserved=0>, or mute the thread<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFIM5GBlwP3VPY6fdF9oIOMuDKYnjAzjks5vWZ8ZgaJpZM4byYSV&data=01%7C01%7Cwheeler%40amnh.org%7Ca5c53fdfff6b4682985a08d6a8186932%7Cbe0003e8c6b9496883aeb34586974b76%7C0&sdata=IVaXfBcfbs1s%2F5srFH7k8m404U2ic12C25BxCabljK4%3D&reserved=0>.

Ward Wheeler
Division of Invertebrate Zoology
American Museum of Natural History
Central Park West at 79th Street
New York, NY 10024-5192
USA
wardwheeler.wordpress.com<http://wardwheeler.wordpress.com>

http://www.amnh.org/our-research/computational-sciences/research/projects/systematic-biology/poy/download

**Comment by recursion-ninja** [comment]
Test out if `algebraic-graphs` can be used for nice `dot` output.

**Comment by Boarders** [comment]
This is (finally) done as of this commit: https://github.com/amnh/PCG/commit/f2b789ea5f9a047e353d7ff720310044313f0e43

Note that along the way I wrote some code to be found in ```app/graphviz-examples``` for generating nice looking network and display tree examples in dot. Should we need to produce more such diagrams this is a good place to start looking. In particular, I can imagine more of the display tree diagrams being extremely useful for when it comes to explaining anything related to that.
