### ISSUE TITLE
Find space leaks in code

### ISSUE THREAD

**Issue by Boarders** [amnh/PCG#149]
We should use the method described [here](https://github.com/ndmitchell/spaceleak) to try to find any space leaks in our code.

**Comment by recursion-ninja** [comment]
The technique described above, while valuable, does not work on an executable as large as ours. It is useful for finding the *first* "space leak" bottleneck, but it is impossible to find problem "space leaks" past the first bottleneck. If the first bottleneck is not resolvable all others cannot be resolved with this technique.

Since our executable has a lot of dynamic allocation during the unification phase, the program cannot run in constant space past that point and any "space leaks" behind that point are masked by the unification phase when using this identification technique. 

Closing as generally ineffective for our executable, unfortunately...

**Comment by Boarders** [comment]
Not that this should be re-opened but (for future spelunkers) there is now a much, much better way to do this by using the [nothunks package](https://hackage.haskell.org/package/nothunks) which has an introductory blog post here: https://www.well-typed.com/blog/2020/09/nothunks/
