### ISSUE TITLE
Generating the set of candidate network edges to add  includes phylogenetically inconsistent edges

### ISSUE THREAD

**Issue by recursion-ninja** [amnh/PCG#73]
Some of the edges generated connect to an ancestor in their path to one of the root nodes. This allows us to construct phylogenetically inconsistent networks when consuming the list of candidate network edges.

**Comment by recursion-ninja** [comment]
Properties that the candidate network edges should satisfy are:

 * The new edge cannot go into an existing edge with source or target network node.

 * Neither of the edges should be ancestral to one another:
   1. Collect the set of ancestral nodes for both edges (excluding the root in the ancestral set).
   2. Perform set intersection of ancestral node sets of the two edges.
   3. If the intersection is empty, there is no time-consistency violation in adding an edge between the two edges.

**Comment by Boarders** [comment]
If we allow creating a new network node from a source edge to a target edge and the source edge contains a root node then the run time system gives a <<loop>> error during the scoring indicating that it has detected an infinite loop. For now I have disallowed this possibility from the candidate edges but this does rule out adding edges we may otherwise wish to have. It may be worth investigating why this is in a separate issue.

**Comment by recursion-ninja** [comment]
We should write a LaTeX document in `doc/tex/` that describes the psuedocode of how to efficiently generate the set of candidate network edges.
